#!/bin/bash
#
# php-fcgi PHP FastCGI daemon
#
# pidfile: /var/run/php-cgi.pid

# Source function library.

PHP=/usr/bin/php5-cgi
PIDFILE=/var/run/php-fastcgi.pid

HOST=127.0.0.1
PORT=9000
CHILDREN=8
USER=www-data
GROUP=www-data

RETVAL=0

case "$1" in
    start)
        echo -n $"Starting php-fastcgi: "
        spawn-fcgi -u $USER -g $GROUP -f $PHP -a $HOST -p $PORT -C $CHILDREN -P $PIDFILE
        RETVAL=$?
        echo
  ;;
    stop)
        echo -n $"Stopping php-fastcgi: "
        killall -w $PHP
        RETVAL=$?
  ;;
    restart)
        echo -n $"Restarting php-fastcgi: "
        killall -w $PHP
        echo
        if [ $? -eq 0 ]; then
          spawn-fcgi -u $USER -g $GROUP -f $PHP -a $HOST -p $PORT -C $CHILDREN -P $PIDFILE
          RETVAL=$?
        fi
  ;;
    status)
        status $PHP
  ;;
    *)
        echo "Usage: php-fastcgi {start|stop|status|restart}"
        exit 1
  ;;
esac
exit $RETVAL
